version: '3.3'
services:
  api:
    image: 192.168.33.22:5000/python:testing
    ports:
      - target: 5000
        published: 80
        protocol: tcp
        mode: host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/v1/info"]
      interval: 10s
      timeout: 3s
      retries: 3
